version: "3.3"
services:

  caddy:
    container_name: app_caddy
    build: ./.docker/caddy
    # links:
    #     # - node_api
    #     - node_www
    #     - go_api
    ports:
        - "8889:80"
        # - "443:443"
    networks:
      - app_net
        
  node_www:
    container_name: app_node_www
    build:
      context: ./server/www/
      dockerfile: ../../.docker/node/www/Dockerfile
    ports:
      - "3000"
    restart: always
    tty: true 
    networks:
      - app_net

  go_api:
    container_name: app_go_api
    build:
      context: ./server/api/
      dockerfile: ../../.docker/go/api/Dockerfile
    ports:
      - "3000"
    restart: always
    tty: true
    privileged: true
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - app_net

  mysql:
    build: ./.docker/mysql
    container_name: app_mysql
    ports:
      - "3305:3305"
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: myapp
    restart: always
    tty: true
    networks:
      - app_net

networks:
  app_net:
    driver: bridge